/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'id' : bigint,
  'pensum' : bigint,
  'name' : string,
  'isActive' : boolean,
}
export interface Entry {
  'id' : bigint,
  'kw' : bigint,
  'entryType' : EntryType,
  'days' : number,
  'year' : bigint,
  'employeeId' : bigint,
  'projectId' : [] | [bigint],
  'notes' : string,
}
export type EntryType = { 'projekteinsatz' : null } |
  { 'ferien' : null } |
  { 'absenz' : null } |
  { 'feiertag' : null };
export interface Holiday {
  'id' : bigint,
  'kw' : bigint,
  'name' : string,
  'year' : bigint,
}
export interface Project {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'isActive' : boolean,
}
export interface UpdateEntry {
  'kw' : bigint,
  'entryType' : EntryType,
  'days' : number,
  'year' : bigint,
  'employeeId' : bigint,
  'projectId' : [] | [bigint],
  'notes' : string,
}
export interface UpdateProject {
  'name' : string,
  'color' : string,
  'isActive' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrustedAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'applyHolidaysToAllEmployees' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateEmployee' : ActorMethod<
    [bigint, string, bigint, boolean],
    bigint
  >,
  'createOrUpdateHoliday' : ActorMethod<
    [bigint, string, bigint, bigint],
    bigint
  >,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllEntries' : ActorMethod<[], Array<Entry>>,
  'getAllHolidays' : ActorMethod<[], Array<Holiday>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'getEntriesForEmployeeYear' : ActorMethod<[bigint, bigint], Array<Entry>>,
  'getEntriesForYear' : ActorMethod<[bigint], Array<Entry>>,
  'getEntry' : ActorMethod<[bigint], [] | [Entry]>,
  'getHoliday' : ActorMethod<[bigint], [] | [Holiday]>,
  'getHolidaysForYear' : ActorMethod<[bigint], Array<Holiday>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getTrustedAdminPrincipals' : ActorMethod<[], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerAsTrustedAdmin' : ActorMethod<[], undefined>,
  'removeTrustedAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'upsertEntry' : ActorMethod<[bigint, UpdateEntry], bigint>,
  'upsertProject' : ActorMethod<[bigint, UpdateProject], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];