/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'pensum' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const EntryType = IDL.Variant({
  'projekteinsatz' : IDL.Null,
  'ferien' : IDL.Null,
  'absenz' : IDL.Null,
  'feiertag' : IDL.Null,
});
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'kw' : IDL.Nat,
  'entryType' : EntryType,
  'days' : IDL.Float64,
  'year' : IDL.Nat,
  'employeeId' : IDL.Nat,
  'projectId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
});
export const Holiday = IDL.Record({
  'id' : IDL.Nat,
  'kw' : IDL.Nat,
  'name' : IDL.Text,
  'year' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UpdateEntry = IDL.Record({
  'kw' : IDL.Nat,
  'entryType' : EntryType,
  'days' : IDL.Float64,
  'year' : IDL.Nat,
  'employeeId' : IDL.Nat,
  'projectId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
});
export const UpdateProject = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrustedAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'applyHolidaysToAllEmployees' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateEmployee' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createOrUpdateHoliday' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getAllHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
  'getEntriesForEmployeeYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Entry)],
      ['query'],
    ),
  'getEntriesForYear' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [IDL.Opt(Entry)], ['query']),
  'getHoliday' : IDL.Func([IDL.Nat], [IDL.Opt(Holiday)], ['query']),
  'getHolidaysForYear' : IDL.Func([IDL.Nat], [IDL.Vec(Holiday)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getTrustedAdminPrincipals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAsTrustedAdmin' : IDL.Func([], [], []),
  'removeTrustedAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'upsertEntry' : IDL.Func([IDL.Nat, UpdateEntry], [IDL.Nat], []),
  'upsertProject' : IDL.Func([IDL.Nat, UpdateProject], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'pensum' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const EntryType = IDL.Variant({
    'projekteinsatz' : IDL.Null,
    'ferien' : IDL.Null,
    'absenz' : IDL.Null,
    'feiertag' : IDL.Null,
  });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'kw' : IDL.Nat,
    'entryType' : EntryType,
    'days' : IDL.Float64,
    'year' : IDL.Nat,
    'employeeId' : IDL.Nat,
    'projectId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
  });
  const Holiday = IDL.Record({
    'id' : IDL.Nat,
    'kw' : IDL.Nat,
    'name' : IDL.Text,
    'year' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UpdateEntry = IDL.Record({
    'kw' : IDL.Nat,
    'entryType' : EntryType,
    'days' : IDL.Float64,
    'year' : IDL.Nat,
    'employeeId' : IDL.Nat,
    'projectId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
  });
  const UpdateProject = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrustedAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'applyHolidaysToAllEmployees' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateEmployee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createOrUpdateHoliday' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getAllHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
    'getEntriesForEmployeeYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Entry)],
        ['query'],
      ),
    'getEntriesForYear' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [IDL.Opt(Entry)], ['query']),
    'getHoliday' : IDL.Func([IDL.Nat], [IDL.Opt(Holiday)], ['query']),
    'getHolidaysForYear' : IDL.Func([IDL.Nat], [IDL.Vec(Holiday)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getTrustedAdminPrincipals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAsTrustedAdmin' : IDL.Func([], [], []),
    'removeTrustedAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'upsertEntry' : IDL.Func([IDL.Nat, UpdateEntry], [IDL.Nat], []),
    'upsertProject' : IDL.Func([IDL.Nat, UpdateProject], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };